# Generated by Django 3.1.13 on 2021-09-24 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
