# Generated by Django 3.1.13 on 2021-09-24 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0003_auto_20210924_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='developertask',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='developertask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submited', 'Submited'), ('Successful', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
