# Generated by Django 3.1.13 on 2021-10-06 19:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0004_auto_20210924_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='solution',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='developertask',
            name='assigned_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Inst'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='developertask',
            name='submit',
            field=models.TextField(default='', max_length=40),
        ),
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('required_points', models.PositiveIntegerField(default=0)),
                ('public', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='project_management.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
