# Generated by Django 3.1.13 on 2021-10-09 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0005_auto_20211006_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developertask',
            name='assigned_by',
            field=models.ForeignKey(default=1, limit_choices_to={'user_type': 'Inst'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developertask',
            name='developer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Inst'}, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='developertask',
            name='submit',
            field=models.TextField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Inst'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
