# Generated by Django 3.1.13 on 2021-09-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Dev', 'Developer'), ('Inst', 'Instructor')], default='Dev', max_length=20),
        ),
    ]
