# Generated by Django 3.1.13 on 2021-10-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='testuser@gmail.com', max_length=254, verbose_name='email address'),
        ),
    ]
